swagger: '2.0'
info:
  title: Ship API
  description: Api to search ship data and images
  version: "0.1.2"
host: api.laivadata.fi
schemes:
  - https
basePath: /v1
consumes:
  - application/json;charset=utf-8
produces:
  - application/json;charset=utf-8
paths:
  /ships:
    get:
      operationId: listShips
      summary: List ships
      description: List ships
      parameters:
        - name: q
          in: query
          description: filter results by free text search
          type: string
        - name: from
          in: query
          description: start from this
          type: string
        - name: size
          in: query
          description: number of results
          type: string
      tags:
        - Ships
      responses:
        200:
          description: An array of ships
          schema:
            type: array
            items:
              $ref: '#/definitions/Ship'
        400:
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        403:
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /ships/{shipId}:
    get:
      operationId: findShip
      summary: Find ship
      description: Find ship
      parameters:
        - name: shipId
          in: path
          description: ship id
          type: string
          required: true
      tags:
        - Ships
      responses:
        200:
          description: Returns a ship
          schema:
            $ref: '#/definitions/Ship'      
        400:
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        403:
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        404:
          description: Ship with specified ID was not found
          schema:
            $ref: '#/definitions/NotFound'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /attachments:
    get:
      operationId: listAttachments
      summary: List attachments
      description: List attachments
      parameters:
        - name: buildnumber
          in: query
          description: filter results by buildnumber
          type: string
      tags:
        - Attachments
      responses:
        200:
          description: An array of attachments
          schema:
            type: array
            items:
              $ref: '#/definitions/Attachment'
        400:
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        403:
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /attachments/{attachmentId}:
    get:
      operationId: findAttachment
      summary: find attachment
      description: find attachments
      parameters:
        - name: attachmentId
          in: path
          description: attachments id
          type: string
          required: true
      tags:
        - Attachments
      responses:
        200:
          description: Single attachment
          schema:
            $ref: '#/definitions/Attachment'
        400:
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        403:
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        404:
          description: Attachment with specified ID was not found
          schema:
            $ref: '#/definitions/NotFound'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /attachments/{attachmentId}/data:
    get:
      produces:
        - application/octet-stream
      operationId: findAttachmentData
      summary: Find attachmentData
      description: Find attachmentData
      parameters:
        - name: attachmentId
          in: path
          description: attachment id
          type: string
          required: true
      tags:
        - Attachments
      responses:
        200:
          description: Returns an attachment data
          schema:
            type: string
            format: binary   
        400:
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        403:
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        404:
          description: Attachment with specified ID was not found
          schema:
            $ref: '#/definitions/NotFound'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
definitions:
  Ship:
    type: object
    properties:
      _id:
        type: string
        format: uuid
        description: Unique identifier for a ship
      buildnumber:
        type: integer
        format: int32
      name:
        type: string
      type_translated:
        type: string
      type:
        type: string
      type_info:
        type: string
      buildyear:
        type: string
      properties:
        type: array
        items:
          $ref: '#/definitions/ShipProperty'
  Attachment:
    properties:
      buildnumber:
        type: integer
        format: int32
      type:
        type: string
      url:
        type: string
      filename:
        type: string
      contenttype:
        type: string
      attachmentdata:
        type: string
  ShipProperty: 
    type: object
    properties:
      property:
        type: string
      value:
        type: string
  InternalServerError:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  Forbidden:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  BadRequest:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  NotFound:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string